name: Generate trends.json (no-api)

on:
  push:
    paths:
      - '*.xlsx'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-trends:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate trends.json
        run: python scripts/generate_trends.py

      - name: Commit trends.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add trends.json
          git commit -m "Auto-generate trends.json" || echo "No changes to commit"
          git push
